version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - docker --version
      - echo "Checking AWS identity..."
      - aws sts get-caller-identity
      - echo "Getting ECR login password..."
      - aws ecr get-login-password --region us-east-1 > /tmp/ecr_password
      - echo "Logging into ECR..."
      - cat /tmp/ecr_password | docker login --username AWS --password-stdin 580953451085.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building backend Docker image..."
      - docker build -t 580953451085.dkr.ecr.us-east-1.amazonaws.com/backend:latest ./starter/backend
      - echo "Building frontend Docker image..."
      - docker build --build-arg REACT_APP_MOVIE_API_URL=http://a42a780e367684155ac035266f9850dc-286608225.us-east-1.elb.amazonaws.com -t 580953451085.dkr.ecr.us-east-1.amazonaws.com/frontend:latest ./starter/frontend

  post_build:
    commands:
      - echo "Pushing backend image..."
      - docker push 580953451085.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      - echo "Pushing frontend image..."
      - docker push 580953451085.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'

