  build:
    name: Docker Build
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=http://a42a780e367684155ac035266f9850dc-286608225.us-east-1.elb.amazonaws.com \
            --tag mp-frontend:${{ github.sha }} \
            starter/frontend